# Generated by Django 3.0.3 on 2020-09-18 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPA', '0002_answer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='updateDate',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updateDate',
        ),
    ]
